service: fcm-delivery

frameworkVersion: '>=1.28.0 <2.0.0'

plugins:
  - serverless-localstack

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  profile: default
  deploymentBucket: ${opt:bucket}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "sqs:SendMessage"
        - "sqs:GetQueueUrl"
      Resource:
        Fn::GetAtt:
          - TargetQueue
          - Arn

package:
  exclude:
    - ./**
  include:
    - ./bin/**

custom:
  localstack:
    debug: true
    stages:
      - local
    host: http://localhost
    autostart: true
    endpoints:
      SNS: http://localhost:4575
      SQS: http://localhost:4576
      SSM: http://localhost:4583
      Lambda: http://localhost:4574
  firebase_service_account_json: ${file(./app/firebase_service_account.json)

functions:
  app:
    handler: bin/app
    reservedConcurrency: 1
    environment:
      FIREBASE_CREDENTIAL: ${self:custom.firebase_service_account_json}
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - TargetQueue
              - Arn
          batchSize: 1

resources:
  Resources:
    TargetQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "FcmDeliveryPlatformTargetQueue-${self:provider.stage}"
