version: '3.2'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 8083:80
    volumes:
      - ./app:/var/www/app/
    depends_on:
      - "php"
    networks:
      - symfony
  php:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    ports:
      - 8081:8081
    env_file:
      - ./app/.env
    volumes:
      - ./app:/var/www/app/
    networks:
      - symfony

networks:
  symfony: