version: '3'
services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - 8083:80
    volumes:
      - ./app:/var/www/app/
    depends_on:
      - "php"
    networks:
      - symfony
    links:
      - "php"
  php:
    build:
      context: ./app
    ports:
      - 8081:8081
    env_file:
      - ./app/.env
    volumes:
      - ./app:/var/www/app/
    networks:
      - symfony

networks:
  symfony: