version: '3.2'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 8082:80
    volumes:
      - ./app:/var/www/src/
    depends_on:
      - "php"
    networks:
      - symfony
  php:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    environment:
      APP_ENV: dev
    volumes:
      - ./app:/var/www/src/
    networks:
      - symfony


networks:
  symfony: