version: '3.2'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 8082:80
    volumes:
      - ./src:/var/www/src/
    depends_on:
      - php-fpm
    networks:
      - symfony
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    environment:
      APP_ENV: dev
    volumes:
      - ./src:/var/www/src/
    networks:
      - symfony


networks:
  symfony: